<Project>
  <PropertyGroup>
    <SticksTargetFramework Condition="'$(SticksTargetFramework)' == ''">net10.0</SticksTargetFramework>
  </PropertyGroup>
  <PropertyGroup Label="Documentation">
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>
</Project>
