<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyTitle>osu.Game.Rulesets.Sticks</AssemblyTitle>
    <OutputType>Library</OutputType>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <RootNamespace>osu.Game.Rulesets.Sticks</RootNamespace>
    <Authors>Zankai LLC</Authors>
    <Company>Zankai LLC</Company>
    <Copyright>Copyright (c) 2026 Zankai LLC</Copyright>
    <Version>0.1.0-dev</Version>
    <OsuGameVersion Condition="'$(OsuGameVersion)' == ''">2026.730.0</OsuGameVersion>
  </PropertyGroup>
  <PropertyGroup Condition="'$(SticksRulesetApi2026818)' == 'true'">
    <DefineConstants>$(DefineConstants);STICKS_RULESET_API_2026_818</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <AssemblyMetadata Include="License" Value="PolyForm Noncommercial 1.0.0 with additional permissions" />
    <AssemblyMetadata Include="LicenseUrl" Value="https://polyformproject.org/licenses/noncommercial/1.0.0/" />
    <AssemblyMetadata Include="RequiredNotice" Value="Copyright (c) 2026 Zankai LLC." />
  </ItemGroup>
  <ItemGroup Condition="'$(OsuSourceRoot)' == ''">
    <PackageReference Include="ppy.osu.Game" Version="$(OsuGameVersion)" />
  </ItemGroup>
  <ItemGroup Condition="'$(OsuSourceRoot)' != ''">
    <ProjectReference Include="$(OsuSourceRoot)\osu.Game\osu.Game.csproj">
      <AdditionalProperties Condition="'$(OsuClientVersion)' != ''">Version=$(OsuClientVersion)</AdditionalProperties>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="osu.Game.Rulesets.Sticks.Tests" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="..\cursors\*.png"
                      Link="Resources\Textures\Cursors\%(Filename)%(Extension)"
                      LogicalName="$(RootNamespace).Resources.Textures.Cursors.%(Filename)%(Extension)" />
    <EmbeddedResource Include="..\Design\sticks_icon.png"
                      Link="Resources\Textures\Icon\sticks_icon.png"
                      LogicalName="$(RootNamespace).Resources.Textures.Icon.sticks_icon.png" />
    <EmbeddedResource Include="Resources\Shaders\*.fs" />
    <EmbeddedResource Include="Resources\sklime_kira.wav"
                      Link="Resources\Samples\UI\ruleset-select-sticks.wav"
                      LogicalName="$(RootNamespace).Resources.Samples.UI.ruleset-select-sticks.wav" />
  </ItemGroup>
</Project>
